### PR TITLE
Update onmotion-bootstrap-modal.js

### PR DESCRIPTION
**Pull request by sabi1981**

### CODE REVIEW

**Review by onmotion — COMMENTED** [review]
Hi.

Why we shouldn't do the preventDefault? And how is it possible that the form doesn't exist (We already listen to the event on it)?

**Comment by sabi1981** [comment]
Hi Alexandr,

Thank you for having a look.

The situation is the following. 
var form = $modal.find('form'); does not exist, no <form> - I do not know why, and/or where should be used. Or where does it comes from.
Now, on the page there are multiple forms and the preventDefault will prevent the submission of every form, because the event listener sits on the document. 
$(document).on('submit', form, ()=>{});
You can read it like, submit event happens anywhere on the document(web page) then tries to find the 'form' but there is no form.
If the 'form' DOM is static (not changing by JS for eg) and exist of course, you can also do $(form).on('click' .... ); and in this case the event listener will sit on the <form> not on the document.
But why is no <form> in the $('#gallery-modal') ? Probably we should dig deeper and solve the root of problem of course. This is just a safety solution to not to break the rest of the app.

**Comment by onmotion** [comment]
Course we should use the explicit **id** instead of form tag in the selector. Can you make it?

PS I know this is a terrible code, but, sorry, I did it a long time ago :)

**Comment by sabi1981** [comment]
I wouldn't say terrible, just requires a bit fine tuning :)
The thing is, I don't know what would be the id of the form, as it isn't generated, and I don't see the code  
where the from should come from.

**Comment by onmotion** [comment]
```js
var $modal = $('#gallery-modal');
```
i don't even understand how the $('#gallery-modal').find('form') selector can affect other forms? Can you explain your bug case?

**Comment by sabi1981** [comment]
Let's do an experiment on any page with jQuery.

Anywhere you click it will console log the "Clicked"
`
let $form = $(document).find('.not-exist-dom');
$(document).on('click', $form, function(){ console.log("Clicked"); });
`
Or for forms, it prevents any form submission.
`
let $form = $(document).find('.not-exist-dom');
$(document).on('submit', $form, function(e) {
     e.preventDefault(); 
     console.log("Clicked");
     return false;
 });
`

**Comment by onmotion** [comment]
it seems like an ambiguous behavior :)
Maybe we just need to change selector like this:

```js
$(document).on("submit", '#gallery-modal form', function(e){
```

**Comment by sabi1981** [comment]
Yes, it works for me!

**Comment by onmotion** [comment]
Can you update the PR?

**Comment by sabi1981** [comment]
Thank you for the help !

**Comment by onmotion** [comment]
Thank you. Pushed the new tag.

**Pull request merged**
